name: mobileappproject
description: A Flutter application for MobileAppProject

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: "0.5.2"
  firebase_auth: "^0.18.3"
  cloud_firestore: "^0.14.1+3"
  firebase_storage: "^5.0.1"
  google_sign_in: "^4.5.1"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
