name: mobileappproject
description: A Flutter application for MobileAppProject

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: "0.5.2"
  firebase_auth: "^0.18.3"
  google_sign_in: "^4.5.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
