name: mobileappproject
description: A Flutter application for MobileAppProject

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: "^0.5.3"
  firebase_auth: "^0.18.3"
  flutter_signin_button: ^1.1.0
  cloud_firestore: "^0.14.1+3"
  firebase_storage: "^5.0.1"
  google_sign_in: 4.5.5
  firebase_ml_vision: ^0.9.10
  image_picker: 0.4.12+1
  fl_chart: ^0.12.0
  flutter_translate: 1.6.0
  translator : 0.1.5
  flutter_local_notifications: ^3.0.2
  rxdart: ^0.25.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
